### ISSUE TITLE
Right To Left Support

### ISSUE THREAD

**Issue by tarek903** [marketplacer/Cosmos#50]
Hi,
first of all i'd like to thank you for this framework but i have a question . i there any plane for this framework to support right to left languages ?

**Comment by evgenyneu** [comment]
Hello @tarek903, good question. The reason I have not implemented it yet is because the App Store does not switch the direction of the star rating control in Arabic:

<img src='https://cloud.githubusercontent.com/assets/880411/21162277/b2011ab6-c1e0-11e6-9521-ac7a404e68d1.png' width='320' alt='Right-to-left language rating control in App Store'>

I am not a right-to-left language user, so I have a question. Is it normal to keep the direction the same for the stars as in English in right-to-left language countries? Or should the star control be flipped?

**Comment by tarek903** [comment]
yea the stars should be flipped
![screen shot 2016-12-14 at 12 31 15 pm](https://cloud.githubusercontent.com/assets/11038057/21178664/4979f008-c1f9-11e6-99a2-3341fb45c9bf.png)

**Comment by evgenyneu** [comment]
Thanks, @tarek903, this needs to be done then.

**Comment by farshadjahanmanesh** [comment]
one approach is reversing everything, swap your empty color with fill color, and minus rank from max rank
rank is 3.5 --> 3 and half filled star and one and half empty star
==> 3.5 - 5 = 1.5 ---> one and half empty, 3 and half filled
when your swap empty and fill colors, cosmos looks like right to left 😄

**Comment by evgenyneu** [comment]
Hehe, clever hack!

**Comment by tarek903** [comment]
@farshadjahanmanesh  Wow .. That actually works thanks

**Comment by evgenyneu** [comment]
Cosmos now supports right-to-left languages from version `8.0`. Thanks for your help @tarek903 and @farshadjahanmanesh.

**Comment by nemexyz** [comment]
Hello,

Update version 8.0.1 in my project, work with an application and a framework that generates error when building it by UIApplication.shared of the RightToLeft support. Can you support framework with API extension?

![captura de pantalla 2017-01-25 a las 11 53 53 a m](https://cloud.githubusercontent.com/assets/19313565/22300303/09b425e8-e2f5-11e6-9f58-3c2db9e08ac4.png)

Thanks...

**Comment by evgenyneu** [comment]
@nemexyz, thank you for reporting this. I have removed `UIApplication.shared` from the code and released version `8.0.2`. Let me know if it still does not compile. The side effect of this, unfortunately, is that right-to-left only works for iOS 9+.

**Comment by evgenyneu** [comment]
Closing, feel free to reopen when needed.
