### ISSUE TITLE
Code-compliant issues

### ISSUE THREAD

**Issue by Sharkesm** [marketplacer/Cosmos#52]
Recently i've downloaded the library and embedded it into my project using Cocoapods ~ 1.1.1. Everything worked fine until when i tried to add Cosmos rating view into table cell and try to manipulate it with different rating values on the controller side and end up getting this error during run-time: 

*** Terminating app due to uncaught exception 'NSUnknownKeyExeption', reason: setValue:forUnderfinedKey:]: this class is not key value coding-compliant for the key RatingView.***

Is there anything that i might have missed, i tried to follow everything as explained at the intro yet this error still exists.

IDE: Xcode ~ 8.2.1

**Comment by evgenyneu** [comment]
Hi @Sharkesm, good question. This error is sometimes caused by a missing link between the view in the Storyboard and the outlet property in the code. I am assuming you subclassed the `UITableViewCell` and in this [cell class](https://github.com/marketplacer/Cosmos/blob/master/Demo/PerformanceTableViewCell.swift) you have an outlet for the cosmos view. Make sure it is correctly linked to the CosmosView in the Storyboard.

For a reference, you can check the demo app, that has a screen with many cosmos views in a table. Let me know how it goes.

<img src="https://raw.githubusercontent.com/marketplacer/Cosmos/master/graphics/Screenshots/cosmos_star_rating_swift_performance.gif" width="320" alt="Cosmos view in a table">

**Comment by Sharkesm** [comment]
Seriously tried to remove the outlet for almost 4 times before posting the problem yet today it worked.

**Comment by evgenyneu** [comment]
No worries, I am glad it works now.
