### ISSUE TITLE
didTouchCosmos closure can capture self 

### ISSUE THREAD

**Issue by andrew8712** [marketplacer/Cosmos#6]
I'd be safer to change this

    cosmosView.didTouchCosmos = { rating in }

to this

    cosmosView.didTouchCosmos = { [unowned self] rating in }

in case if we'd use this code within view controller. Otherwise `didTouchCosmos` closure captures a reference to `self` and retain cycle is created.

**Comment by evgenyneu** [comment]
Hi, yes, I agree, which part of code are you referring to?

**Comment by andrew8712** [comment]
README

**Comment by evgenyneu** [comment]
I would not put the capture to this example in the readme, which currently is:

```Swift
// Receive user input
cosmosView.didTouchCosmos = { rating in }
```

In my opinion, putting capture list will make the example a little bit complicated and move the focus away from its main purpose. Remember, we are not teaching people Swift language here, but rather explaining how to use the library. Note that in some situation people will not need to use capture list at all, or they will need to use `[weak self]` instead of `[unowned self]`. Explaining all those nuances in this readme is a bit out of the scope of this document and could be distractive. Thank you for your feedback.
